### ISSUE TITLE
Create and design a standard schedule component 

### ISSUE THREAD

**Issue by FurKay00** [FurKay00/TimetablePlanning#1]
A schedule component will be necessary to visualize the current state of a schedule regardless of the user. It should also be reusable. 
The following points need to be achieved:
- [x] A schedule should consist of time units which are flexible in size (depending on the current scale).
- [x] Multiple time units should be allowed to exist simultaneously (e.g. concurrent appointments)
- [x] The schedule should show the current time (e.g. a red line)
- [x] The scales are the weekdays (mandatory within the week, optional within the weekends)
- [x] The scales could also be reduced to a day
