### ISSUE TITLE
Create component to visualize estimated distance and time between two appointments

### ISSUE THREAD

**Issue by FurKay00** [FurKay00/TimetablePlanning#3]
Every role should be able to see the estimated distance and time between two appointments. The following points need to be achieved:
- [ ] Checkbox to show the estimated distance and time between two appointments
- [ ] Visualisation/Design of this feature
- [ ] Implementation of algorithm/system to determine the shortest time and way (propably graphs and djikstra)
- [ ] Implementation of system to check, whether the distance between the previous appointment and the anticipated appointment is too short (signaling the secretary that there may be conflicts)
