### ISSUE TITLE
Creation of new appointments

### ISSUE THREAD

**Issue by FurKay00** [FurKay00/TimetablePlanning#4]
Only secretaries are allowed to create new and update previous appointments. Thus, a way to enable these functions must be implemented with the following criteria:
- [x] Button to create new appointment
- [x] New modal dialog for the creation of new appointments. Should include the following:
  - Choose between single appointment and 'block appointment' (and only show the corresponding attributes)
  - Show a preview of proposed appointment/s
  - Visualization:
    - Appointment clash for lecturer
    - Room size inadequate for students
    - Time difference too small between proposed appointment and the ones bevore/after that
 
Details:
- [x] Single appointment (attributes):
  - Choose type 
  - Choose appointment name
  - Choose date
  - Choose start time
  - Choose end time
  - Choose lecturers
  - Choose rooms
  
- [x] Block appointment (attributes):
  - Choose module (predefined hours)
  - Choose start date
  - Choose regular start time 
  - Choose frequency per week
  - Choose max. hours
  - Choose lecturers
  - Choose rooms

- [x] Other functions:
  - Drag and drop newly proposed appointments for better usability
